### ISSUE TITLE
Does not update after a revert-buffer

### ISSUE THREAD

**Issue by artagnon** [alefragnani/atom-read-only-indicator#2]
How do I start editing the file post `p4 edit`?

**Comment by alefragnani** [comment]
I didn't know **revert-buffer** package, and designed **read-only-indicator** based on _navigating between the documents_, instead of _detecting OS changes_. But it would be a great idea if **revert-buffer** had published services, so anyone could detect when it is called.

I will take a look if there is something I can do to detect it. Or maybe, update **revert-buffer** to publish this service.

**Comment by artagnon** [comment]
So, in Emacs, a file doesn't automatically get a `[RW]` status after a `p4 edit` -- but, I suspect `p4e` does a `revert-buffer` after the `p4-edit`; most importantly, `revert-buffer` triggers a full re-read. I don't think you can poll for changes in the filesystem unless you use a dedicated `fswatch` daemon or something.

**Comment by alefragnani** [comment]
Depends on https://github.com/atom/revert-buffer/issues/6

**Comment by alefragnani** [comment]
I'm closing this issue because the Atom issue that it depends on has no update from Atom team members for a long time.

I'm subscribed to that issues, so if/when it is updated, I'll be notified.


Thank you for your understanding.
