### ISSUE TITLE
Autorefresh if file ReadOnly/Write mode is modified

### ISSUE THREAD

**Issue by zarathosss** [alefragnani/atom-read-only-indicator#8]
Hello,

would be nice to have an automatic refresh of the status if the mode "ReadOnly/Write" of the file is modified.
Currently need to change the tabpage and comes back to update the status.
This is important that the status is always up to date, so that I can have confidence in this status and not always switch the tabpages to be sure I've an updated status.

**Comment by jmtoniolo** [comment]
I looked and looked and there is no listener we can subscribe to that will pick on file permission status changes. This is probably especially true because different operating systems would require custom implementations in order for atom to expose a callback like that. We could tie the check to an async timer? Or you could click the icon to refresh it? What do you guys think?

**Comment by alefragnani** [comment]
Hi @jmtoniolo 

If there is no _built in_ listener, I see two alternatives:

* Use an **async timer**, as you described
* Use a **watcher**, like `fs.watch` and `chokidar`
* Interact with some other Atom package which provides a `watcher`

**Comment by jmtoniolo** [comment]
```
fs.watch( filePath, (event, filename ) ->          
          @subscribeToActiveTextEditor
          console.log 'watch triggered'
          )
```

so this does print to the console, the issue is that anonymous function is inside the fs namespace so none of our class or functions are available. @subscribeToActiveTextEditor() says no function exists because @ (this) is set to the file system object.

##update, I actually figured it out, ill fork and do a pull request tonight
